export const propsColumn = [
  { label: 'Property', key: 'property' },
  { label: 'Type', key: 'type' },
  { label: 'Default', key: 'default' },
  { label: 'Description', key: 'description' },
];

export const componentsMenus = [
  {
    id: 'foundation',
    label: 'Foundation',
    href: null,
    items: [
      { id: 'colors', label: 'Colors', href: '/components/foundation/colors' },
      { id: 'typography', label: 'Typography', href: '/components/foundation/typography' },
      { id: 'icons', label: 'Icons', href: '/components/foundation/icons' },
      { id: 'grid', label: 'Grid', href: '/components/foundation/grid' },
      { id: 'shadow', label: 'Shadow', href: '/components/foundation/shadow' },
      { id: 'motion', label: 'Motion', href: '/components/foundation/motion' },
      { id: 'breakpoints', label: 'Breakpoints', href: '/components/foundation/breakpoints' },
    ],
  },
  {
    id: 'interaction',
    label: 'Interaction',
    href: null,
    items: [
      {
        id: 'splitText',
        label: 'Split Text',
        href: '/components/interaction/splitText',
      },
    ],
  },
  {
    id: 'common',
    label: 'Common',
    href: null,
    items: [
      { id: 'alert', label: 'Alert', href: '/components/common/alert' },
      { id: 'avatar', label: 'Avatar', href: '/components/common/avatar' },
      { id: 'badge', label: 'Badge', href: '/components/common/badge' },
      { id: 'button', label: 'Button', href: '/components/common/button' },
      {
        id: 'buttongroup',
        label: 'ButtonGroup',
        href: '/components/common/buttonGroup',
      },
      {
        id: 'checkbox',
        label: 'Checkbox',
        href: '/components/common/checkbox',
      },
      { id: 'datepicker', label: 'DatePicker', href: '/components/common/datepicker' },
      { id: 'dialog', label: 'Dialog', href: '/components/common/dialog' },
      { id: 'drawer', label: 'Drawer', href: '/components/common/drawer' },
      { id: 'dropdown', label: 'Dropdown', href: '/components/common/dropdown' },
      // { id: 'icon', label: 'Icon', href: '/components/common/icon' },
      // { id: 'image', label: 'Image', href: '/components/common/image' },
      // { id: 'input', label: 'Input', href: '/components/common/input' },
      // { id: 'link', label: 'Link', href: '/components/common/link' },
      // { id: 'loading', label: 'Loading', href: '/components/common/loading' },
      // { id: 'pagination', label: 'Pagination', href: '/components/common/pagination' },
      // { id: 'radioButton', label: 'RadioButton', href: '/components/common/radioButton' },
      // { id: 'select', label: 'Select', href: '/components/common/select' },
      // { id: 'skeleton', label: 'Skeleton', href: '/components/common/skeleton' },
      // { id: 'slider', label: 'Slider', href: '/components/common/slider' },
      // { id: 'switch', label: 'Switch', href: '/components/common/switch' },
      // { id: 'table', label: 'Table', href: '/components/common/table' },
      // { id: 'tabs', label: 'Tabs', href: '/components/common/tabs' },
      // { id: 'tag', label: 'Tag', href: '/components/common/tag' },
      // { id: 'toast', label: 'Toast', href: '/components/common/toast' },
      // { id: 'tooltip', label: 'Tooltip', href: '/components/common/tooltip' },
      // { id: 'tree', label: 'Tree', href: '/components/common/tree' },
      // { id: 'upload', label: 'Upload', href: '/components/common/upload' },
      // { id: 'video', label: 'Video', href: '/components/common/video' },
      // { id: 'carousel', label: 'Carousel', href: '/components/common/carousel' },
      // { id: 'colorPicker', label: 'ColorPicker', href: '/components/common/colorPicker' },
      // { id: 'fileInput', label: 'FileInput', href: '/components/common/fileInput' },
      // { id: 'linkButton', label: 'LinkButton', href: '/components/common/linkButton' },
      { id: 'progress', label: 'Progress', href: '/components/common/progress' },
      { id: 'textinput', label: 'TextInput', href: '/components/common/textInput' },
    ],
  },
  // {
  //   id: 'layout',
  //   label: 'Layout',
  //   href: null,
  //   items: [
  //     {
  //       id: 'snb',
  //       label: 'Side Navigation Bar',
  //       href: '/components/layout/snb',
  //     },
  //     {
  //       id: 'gnb',
  //       label: 'Global Navigation Bar',
  //       href: '/components/layout/gnb',
  //     },
  //   ],
  // },
];

export const componentsImages = [
  {
    id: 'alert',
    label: 'Alert',
    src: '/image/alert_thumbnail.png',
    href: '/components/common/alert',
    alt: 'Alert Thumbnail',
  },
  {
    id: 'avatar',
    label: 'Avatar',
    src: '/image/avatar_thumbnail.png',
    href: '/components/common/avatar',
    alt: 'Avatar Thumbnail',
  },
  {
    id: 'badge',
    label: 'Badge',
    src: '/image/badge_thumbnail.png',
    href: '/components/common/badge',
    alt: 'Badge Thumbnail',
  },
  {
    id: 'buttonGroup',
    label: 'ButtonGroup',
    src: '/image/buttongroup_thumbnail.png',
    href: '/components/common/buttonGroup',
    alt: 'Button Group Thumbnail',
  },
  {
    id: 'datePicker',
    label: 'DatePicker',
    src: '/image/datepicker_thumbnail.png',
    href: '/components/common/datepicker',
    alt: 'Date Picker Thumbnail',
  },
  {
    id: 'dialog',
    label: 'Dialog',
    src: '/image/dialog_thumbnail.png',
    href: '/components/common/dialog',
    alt: 'Dialog Thumbnail',
  },
  {
    id: 'drawer',
    label: 'Drawer',
    src: '/image/drawer_thumbnail.png',
    href: '/components/common/drawer',
    alt: 'Drawer Thumbnail',
  },
  {
    id: 'dropdown',
    label: 'Dropdown',
    src: '/image/dropdown_thumbnail.png',
    href: '/components/common/dropdown',
    alt: 'Dropdown Thumbnail',
  },
];
